name: Model

on:
  push:
    branches: [ "master" ]
    paths:
      - 'WebApi1C8Exchange.Models/WebApiDocumentsExchange.Models.csproj'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2.2.0
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: 'WebApi1C8Exchange.Models/WebApiDocumentsExchange.Models.csproj'
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: false
