name: UI-Controls

on:
  push:
    branches: 
      - master
    paths:
      - 'sabatex.Blazor.UIControls/sabatex.Blazor.UIControls.csproj'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
           dotnet-version: 6.0.x
 
      - name: build
        run: dotnet build sabatex.Blazor.UIControls/sabatex.Blazor.UIControls.csproj
      - name: Create the package
        run: dotnet pack --configuration Release sabatex.Blazor.UIControls/sabatex.Blazor.UIControls.csproj
      - name: Publish the package to nuget.org
        run: dotnet nuget push sabatex.Blazor.UIControls/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

